### ISSUE TITLE
Included task variable defaults don't carry into parent tasks

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/maru-runner#121]
### Environment

Device and OS: popOS 22.04
App version: v0.2.1
Kubernetes distro being used: N/A
Other: N/A

### Steps to reproduce

1. Create two task files like the below:

`tasks.yaml`:
```
includes:
  - incl: ./include.yaml
```

`include.yaml`:
```
variables:
  - name: ECHO
    default: kitteh

tasks:
  - name: echo
    actions:
      - cmd: echo $ECHO
```

2. Run the included task with `maru run incl:echo`

### Expected result

`kitteh` is echoed

### Actual Result

Nothing is echoed

### Visual Proof (screenshots, videos, text, etc)

![image](https://github.com/defenseunicorns/maru-runner/assets/3977569/0f790c78-e367-4bc1-a0e9-1f2c7c812189)

### Severity/Priority

Medium - `--set` still works but this is likely not expected behavior for defaults

### Additional Context

Currently affecting uds-common lula lint task: https://github.com/defenseunicorns/uds-common/pull/147
