### ISSUE TITLE
envPath doesn't play nice with includes

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/maru-runner#129]
### Environment

App version: UDS CLI v0.13.0

### Steps to reproduce

- Create tasks.yaml
```yaml
includes:
  - bar: subdir/bar.yaml

tasks:
  - name: hello
    actions:
      - task: bar:hello
```
- Create .env
```
KENOBI="Hello There!"
```
- Create subdir/bar.yaml
```yaml
tasks:
  - name: hello
    envPath: ../.env
    actions:
      - cmd: echo "$KENOBI"
```

Given the above, if I run `uds run bar:hello` I correctly get `"Hello There!"`. If I run `uds run hello` I don't.

If I change envPath to `.env` then `uds run hello` works fine and `uds run bar:hello` throws:

```
ERROR:  Failed to run action: open subdir/.env: no such file or directory
```

**Comment by RothAndrew** [comment]
IMO paths should always be relative to the source file directory. So, in the example above the correct value for envPath should be `../.env` and both `uds run hello` and `uds run bar:hello` should act the same

**Comment by RothAndrew** [comment]
Similar issues will be found in `actions.dir` and `actions.cmd`

**Comment by RothAndrew** [comment]
Workaround:

```yaml
# subdir/bar.yaml

tasks:
  - name: hello
    actions:
      - cmd: |
             set -a; source .env; set +a
             echo "$KENOBI"
```

**Comment by RothAndrew** [comment]
Note for github actions runners, for some reason `sh` doesn't have `source` so you'll get an error `source: not found`. Do this instead:

```yaml
tasks:
  - name: hello
    actions:
      - cmd: |
          set -a; source .env; set +a
          echo "$KENOBI"
        shell:
          darwin: bash
          linux: bash
```
