### ISSUE TITLE
Use default var value on imported tasks

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/maru-runner#133]
### Environment
Mac M3
Maru v0.2.2
### Steps to reproduce
Create the following files
```
# import.yaml
variables:
  - name: REF
    description: "reference for the runtime image and zarf package"
    default: alpha

tasks:
  - name: echo-ref
    description: "echo the ref"
    actions:
      - cmd: echo ${REF}
```
```
# tasks.yaml
includes:
  - foo: import.yaml
```

Now run the imported task with `maru run foo:echo-ref`

### Expected result
I should see the default value "alpha` echo'd to my terminal

### Actual Result
I only see the standard Maru output, no echo

### Visual Proof (screenshots, videos, text, etc)

![Screenshot 2024-07-29 at 11 48 00 AM](https://github.com/user-attachments/assets/e6374596-48fd-446c-a47f-301fd0db7e34)
