### ISSUE TITLE
Unable to pass in CLI variable override unless default is set for variable

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/maru-runner#136]
Given the following task.yaml referenced elsewhere with an includes: ./path/to/local/file, the subsequent issue is encountered.

```
  - name: plan-tofu
    inputs:
      env:
        description: "Environment to apply to"
        required: true
        type: string
        # default: "please-set-your-env-variable"
    actions:
      - cmd: |
          tofu init -backend-config="./config/${ENV}/backend.tfconfig"
          tofu plan       -var-file="./config/${ENV}/vars.tfvars"
        description: "Initialize & Plan Terraform for Environment"
        mute: false
```

`uds run local:plan-tofu --set=ENV=blah`

```
     ERROR:  Failed to run action: task local:plan-tofu is missing required inputs: env
```

If I uncomment the default and run the same command, I am able to override it with the CLI flag

```                                                                                                                                                                   
     Initializing the backend...                                                                                                                                   
     Initializing modules...    
```

**Comment by ericwyles** [comment]
@zachariahmiller I think this is similar to / in the same part of the code as the issue where you can't call tasks with inputs from the cli at all (unless they are wrapped in another task). Wondering if your pr #135 might actually fix this too?

**Comment by zachariahmiller** [comment]
I have a wip pr to enable calling tasks with inputs directly in addition to the work to allow conditionals, however I don't think that will resolve this issue as inputs and set vars are still distinctly different. 

However, I think in the example if the default was ${ENV} then it would work once those changes are finished and merged in.

**Comment by Racer159** [comment]
@ntwkninja does this work?

```
variables:
  - name: ENV

tasks:
 - name: plan-tofu
    inputs:
      env:
        description: "Environment to apply to"
        required: true
        type: string
        default: "${ENV}"
    actions:
      - cmd: |
          tofu init -backend-config="./config/${ENV}/backend.tfconfig"
          tofu plan       -var-file="./config/${ENV}/vars.tfvars"
        description: "Initialize & Plan Terraform for Environment"
        mute: false
```

**Comment by ntwkninja** [comment]
This is what I've been testing against. Regardless of if there are variables in either file or no variables, as well as, if I use ${{ .inputs.env }} or ${ENV} in the cmd: everything seems to behave the same.


```
# ../tasks.yaml

# yaml-language-server: $schema=https://github.com/defenseunicorns/maru-runner/blob/main/tasks.schema.json

tasks:
  - name: plan-tofu
    inputs:
      env:
        description: "Environment to apply to"
        required: true
        type: string
        default: "${ENV}"
    actions:
      - cmd: |
          tofu init -backend-config="./config/${{ .inputs.env }}/backend.tfconfig"
          tofu plan       -var-file="./config/${{ .inputs.env }}/vars.tfvars"
        description: "Initialize & Plan Terraform for Environment"
        mute: false
```

```
#  tasks.yaml

# yaml-language-server: $schema=https://github.com/defenseunicorns/maru-runner/blob/main/tasks.schema.json

variables:
  - name: "ENV"
    pattern: "^(rdte|production)$"

includes:
  - local: ../tasks.yaml

tasks:
  - name: plan-tofu
    actions:
      - task: local:plan-tofu
```
