### ISSUE TITLE
Update env field that only applies to the cmd and wait task types to also work with task reference

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/maru-runner#144]
### Is your feature request related to a problem? Please describe
the env field only applies to the cmd and wait task types currently (not task references)

When implemented, this should work:

```yaml

  - name: create-doug
    actions:
      - task: setup:create-doug-user
        env:
          - KEYCLOAK_GROUP=/UDS Core/Admin
              
```
