### ISSUE TITLE
Update maru to allow mixed case variable names

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/maru-runner#148]
### Is your feature request related to a problem? Please describe

Maru or at least the schema only allows upper case letters in the variable names. This ticket it to do the following:

1. validate if this is a real issue in maru or just a schema issue
2. if its a real issue modify maru to allow mixed case characters in variable names
3. update the schema to reflect that mixed case characters are allowd

### Additional context

This shows a schema error:
```yaml
variables:
  - name: myVariable
    default: "value"
```

This does not:
```yaml
variables:
  - name: MY_VARIABLE
    default: "value"
```
