### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by JaseKoonce** [defenseunicorns/maru-runner#167]
### Is your feature request related to a problem? Please describe

Occasionally the default maru runner message really detracts from the readability of the output. Because it just uses the first line to report the success it often doesn't really doesn't add much to my experience. For the most part I already add messages in my tasks so seeing these extra messages take away from the experience. Allowing for either a global or per task silent mode to get rid of the default messages would be really nice.

Current implantation:
```
task.yaml

tasks:
  - name: example-task
    actions:
      - cmd: echo "success message with greater detail"
```

Output : * note the duplication 
```
     success message with greater detail                                                                                                                                
  ✔  Completed "echo \"success message with greater detail\""   
```

With Silent mode enabled:
```
task.yaml

default:
  SilentMode: true # global default

tasks:
  - name: example-task
   SilentMode: true # per task option
    actions:
      - cmd: echo "success message with greater detail"
```
Output:
```
     success message with greater detail                                                                                                                                
```
