### ISSUE TITLE
Call tasks with inputs from the cli

### ISSUE THREAD

**Issue by AustinAbro321** [defenseunicorns/maru-runner#17]
### Is your feature request related to a problem? Please describe

I would like to be able to require inputs on my tasks and run those commands from the command line

### Describe the solution you'd like

- **Given** I have a task that looks like build-pkg below
- **When** I run uds run build-pkg --input pkg=my_pkg
- **Then** the task is ran with the input

```yaml
  - name: build-pkg
    description: build a package
    inputs:
      pkg:
        description: pkg to build
        required: true
    actions:
      - cmd: cd "${PKG}" &&  go build -o ../build/${PKG} .
        description: "build pkg"
```
