### ISSUE TITLE
Environment Variable Substitution in Task Inputs `default:` field

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/maru-runner#194]
### Is your feature request related to a problem? Please describe

I'd like to be able to make the value of an environment variable the default for an input.

### Describe the solution you'd like

- **Given** I have a task file like this:

```yaml
tasks:
  - name: login-registry
    inputs:
      registry-url:
        description: The URl of the container registry to login to
        # CI_REGISTRY is a built-in GitLab CI/CD variable
        default: ${CI_REGISTRY}
        required: true
      registry-uer:
        description: The username to use when doing the registry login
        # CI_REGISTRY_USER is a built-in GitLab CI/CD variable
        default: ${CI_REGISTRY_USER}
        required: true
      registry-password:
        description: The password to use when doing the registry login
        default: ${CI_REGISTRY_PASSWORD}
        required: true
        mute: true
    actions:
      - description: Login to the container registry
        cmd: |
          uds zarf tools registry login -u "${{ index .inputs "registry-user" }}" -p "${{ index .inputs "registry-password" }}" "${{ index .inputs "registry-url" }}"
        mute: true
```
and I'm running in A GitLab CI pipeline

- **When** the task is run without any other provided configuration
- **Then** it completes successfully, since the CI_REGISTRY, CI_REGISTRY_USER, and CI_REGISTRY_PASSWORD environment variables are already set by GitLab

### Describe alternatives you've considered

I've been beating my head against the wall for a couple of days now trying to figure out a nice way to do this and nothing it working. The alternative would be to abandon my effort to use `inputs` and go back to `variables` which are, IMO, not as good as inputs due to the lack of things such as `description:` and the ability to set something as deprecated.

### Additional context

Currently if you make that task, the default value is the unsubstituted string. For example, the default value of `registry-url` is the fixed, unsubstituted string `${CI_REGISTRY}`
