### ISSUE TITLE
Unable to use Environment Variable Substitution in an included task

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/maru-runner#195]
### Environment

Device and OS:
App version: main
Kubernetes distro being used:
Other:

### Steps to reproduce

1. Make a tasks.yaml that looks like:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/maru-runner/refs/heads/main/tasks.schema.json
includes:
  - build: tasks/build.yaml
tasks:
  - name: login-registry
    inputs:
      registry-url:
        description: The URl of the container registry to login to
        # CI_REGISTRY is a built-in GitLab CI/CD variable
        default: ${CI_REGISTRY}
        required: true
      registry-uer:
        description: The username to use when doing the registry login
        # CI_REGISTRY_USER is a built-in GitLab CI/CD variable
        default: ${CI_REGISTRY_USER}
        required: true
      registry-password:
        description: The password to use when doing the registry login
        default: ${CI_REGISTRY_PASSWORD}
        required: true
    actions:
      - description: Login to the container registry
        cmd: |
          echo "${{ index .inputs "registry-url" }}"
          if [ -z "${{ index .inputs "registry-url" }}" ]; then
            echo "Doh! registry-url was empty!"
            exit 1
          fi
```

2. and another file `tasks/build.yaml` that looks like:

```yaml
tasks:
  - name: login-registry
    inputs:
      registry-url:
        description: The URl of the container registry to login to
        # CI_REGISTRY is a built-in GitLab CI/CD variable
        default: ${CI_REGISTRY}
        required: true
      registry-uer:
        description: The username to use when doing the registry login
        # CI_REGISTRY_USER is a built-in GitLab CI/CD variable
        default: ${CI_REGISTRY_USER}
        required: true
      registry-password:
        description: The password to use when doing the registry login
        default: ${CI_REGISTRY_PASSWORD}
        required: true
    actions:
      - description: Login to the container registry
        cmd: |
          echo "${{ index .inputs "registry-url" }}"
          if [ -z "${{ index .inputs "registry-url" }}" ]; then
            echo "Doh! registry-url was empty!"
            exit 1
          fi
```

NOTE THAT THE TASK IS THE EXACT SAME IN BOTH CASES

3. Run `export CI_REGISTRY=foo`
4. Run `maru run login-registry`
5. Run `maru run build:login-registry`

### Expected result

Both tasks run exactly the same way

### Actual Result

`maru run login-registry` runs great, exactly as expected. It echoes "foo". `maru run build:login-registry` throws `sh: ${{ index .inputs "registry-url" }}: bad substitution`

### Additional Context

Tested on Maru v0.5.0 as well, same behavior.
