### ISSUE TITLE
Unable to use go templating and a "colon space" (`: `) in the same cmd

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/maru-runner#199]
### Environment

Device and OS:
App version: main
Kubernetes distro being used:
Other:

### Steps to reproduce

1. Make a tasks file with:
``` yaml
- name: inputs-test
  inputs:
    test-input:
      default: hello!
  actions:
    - cmd: |
        echo "This will fail because it uses go templating AND a "colon space"!!!: ${{index .inputs "test-input"}}"
    - cmd: |
        echo "This will succeed because it uses go templating and no "colon space"!!! ${{index .inputs "test-input"}}"
```

### Expected result

both cmds run successfully

### Actual Result

The first one fails due to the `: ` ("colon space")

### Additional Context

Add any other context or screenshots about the technical debt here.

**Comment by zachariahmiller** [comment]
here are two workarounds:

```yaml
tasks: 
  - name: inputs-test
    inputs:
      test-input:
        default: hello!
    actions:
      - cmd: |
          echo "This will succeed because it uses go templating and no "colon space"!!! ${{index .inputs "test-input"}}"
      - cmd: |
          echo "This doesnt fail because it uses go normal env representation of the input AND a "colon space"!!!: $INPUT_TEST_INPUT"
      - cmd: |
          echo "This doesnt fail because it uses different quoting to overcome go templating AND a "colon space"!!! issue"':'" ${{ index .inputs "test-input" }}"
      - cmd: |
          echo "This will fail because it uses go templating AND a "colon space"!!!: ${{index .inputs "test-input"}}"
```

Output:
```
     This will succeed because it uses go templating and no colon space!!! hello!                                                                                                         
  ✔  Completed "echo \"This will succeed because it uses go templating and..."                                                                                                            
     This doesnt fail because it uses go normal env representation of the input AND a colon space!!!: hello!                                                                              
  ✔  Completed "echo \"This doesnt fail because it uses go normal env repr..."                                                                                                            
     This doesnt fail because it uses different quoting to overcome go templating AND a colon space!!! issue: hello!                                                                      
  ✔  Completed "echo \"This doesnt fail because it uses different quoting ..."                                                                                                            
     sh: !!!: ${{index .inputs "test-input"}}: bad substitution     
```
