### ISSUE TITLE
Add a `.env` to the template data

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/maru-runner#200]
### Is your feature request related to a problem? Please describe

When I am using templates I'd like to be able to say `${{ index .env "SOME_ENV_VAR" }}` to grab the value of the shell environment variable SOME_ENV_VAR.

#### Scenario 1
- **Given** I run:
```
export SOME_ENV_VAR=foo
```
and have a tasks.yaml of:
```yaml
  - name: my-task
    actions:
      - cmd: |
          echo "${{ index .env "SOME_ENV_VAR" }}"
```
- **When** I run `maru run my-task`
- **Then** it echoes "foo"

#### Scenario 2
- **Given** I run:
```
unset SOME_ENV_VAR
```
and have a tasks.yaml of:
```yaml
  - name: my-task
    actions:
      - cmd: |
          echo "${{ index .env "SOME_ENV_VAR" }}"
```
- **When** I run `maru run my-task`
- **Then** it echoes an empty string

### Describe alternatives you've considered

(optional) A clear and concise description of any alternative solutions or features you've considered.
