### ISSUE TITLE
Allow go templating in `inputs.default`

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/maru-runner#201]
### Is your feature request related to a problem? Please describe

I'd like to use go templating in `inputs.default`

#### Use Case 1
- **Given** I run
```
export SOME_ENV_VAR=foo
```
and have a tasks.yaml of:
```yaml
  - name: templating-in-default-test
    inputs:
      test-input:
        default: ${{ index .env "SOME_ENV_VAR" }}
        required: true
    actions:
      - cmd: |
          echo "${{ index .inputs "test-input" }}"
```
- **When** I run `uds run templating-in-default-test`
- **Then** It echoes "foo".

#### Use Case 2
- **Given** I run
```
unset SOME_ENV_VAR
```
and have a tasks.yaml of:
```yaml
  - name: templating-in-default-test
    inputs:
      test-input:
        default: ${{ index .env "SOME_ENV_VAR" }}
        required: true
    actions:
      - cmd: |
          echo "${{ index .inputs "test-input" }}"
```
- **When** I run `uds run templating-in-default-test`
- **Then** It fails and says the required input "test-input" was not set

### Describe alternatives you've considered

(optional) A clear and concise description of any alternative solutions or features you've considered.

### Additional context

#200 would be needed first for me to be able to do what is stated in this example.
