### ISSUE TITLE
unintuitive bad substitution error

### ISSUE THREAD

**Issue by Arsinic** [defenseunicorns/maru-runner#211]
### Environment

Device and OS: MacOS
App version: 0.6.0
Kubernetes distro being used: K3d
Other:

### Steps to reproduce

1.  Create a simple task that has inputs and in a command block reference an input that doesn't exist (like a typo). 

```
- name: create-package
    description: Build a zarf package
    inputs:
      dir:
        description: the directory containing the zarf.yaml file
        default: "."
      arch:
        description: the architecture to create the package with
        default: amd64
      options:
        description: additional options to pass to the Zarf package create command
        default: ""
    actions:
      - description: Build the zarf package
        cmd: |
          uds zarf package create ${{ .inputs.dir }} ${{ .inputs.options }} --confirm --no-progress --architecture="${{ .inputs.arc }}"
```

### Expected result

When I do a `maru run create-package --with dir=package --with arch=arm64` the error references a bad substitution at `${{ .inputs.arc }}"` since its misspelled from the actual input of `arch`

### Actual Result
Instead the error references a bad substitution of  `${{ .inputs.dir }}`

```     
bash: ${{ .inputs.dir }}: bad substitution                                                                                                                                                                                                                                                                 
     ERROR:  Failed to run action: command "Build the zarf package" timed out after 0 seconds 
```

### Visual Proof (screenshots, videos, text, etc)



### Severity/Priority
Low

### Additional Context
Just wasted 20 minutes looking at trying to fix the wrong input :(

Add any other context or screenshots about the technical debt here.
