### ISSUE TITLE
Ensure Runner Templating is consistent

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/maru-runner#83]
When creating task that has inputs such as the one below, you can use Go templating in the actions:
```yaml
  - name: no-default
    inputs:
      no-default:
        description: has no default
    actions:
      - cmd: |
          echo success + ${{ index .inputs "no-default" }}
```
Ensure that you can use the same Go templating in Actions that don't have an `inputs` key; in other words, make templates consistent in the runner
