### ISSUE TITLE
Prompts for user input are swallowed by progress indicator

### ISSUE THREAD

**Issue by marshall007** [defenseunicorns/maru-runner#88]
### Environment

Device and OS: `Pop!_OS 22.04 LTS`
App version: `uds version: v0.10.4-6-gdf4aa09`
Kubernetes distro being used: N/A

### Steps to reproduce

See https://github.com/defenseunicorns/uds-package-mattermost/pull/65/files#r1602116776 as an example.

```yaml
tasks:
  - name: ui
    description: Mattermost UI Checks
    actions:
      - cmd: npm ci
        dir: tests
      - cmd: npx playwright install --with-deps
        dir: tests
      - cmd: npx playwright test
        dir: tests
```

`npx playwright install --with-deps` appears to hang, but is actually prompting for sudo password.

### Expected result

Ability to capture input on interactive commands or at least indicate to the user that the command is prompting for input.

### Actual Result

Current behavior makes it appear as though the command is timing out.
